### ISSUE TITLE
Installation of isgl 1.2.4 from git failed (missing Isgl3dMathTypes.h)

### ISSUE THREAD

**Issue by juan-cardelino** [stuartcaunt/isgl3d#38] opened 2012-03-14 11:49 UTC
```
       I've tried to install ISGL 1.2.4 from git, and after installing the templates, the created project doesn't work. Seems that "Isgl3dMathTypes.h" is not getting copied to the project.
```

The error appears in line 27 of Isgl3dVector.h:
'Isgl3dMathTypes.h' file not found

Is it a bug, or am I missing something.
Thanks in advance.
Best regards,
                    Juan

----------- setup details -----------
Here is the git version I'm using (from 2012.03.14):

> git log --pretty=format:'%h' -n 1
> ed6b1c7

XCode version 4.3.1

**Comment by HolgerW1** [comment] 2012-03-14 15:18
Duplicate of #15
iSGL3D does compile, it's the template that needs to be updated

**Closed as completed by HolgerW1** 2012-03-14 15:18 UTC
